Repository Zyllos/tts_ftc_base_lua_scripts, pull requests merged in 2021-02, with the labels that each got.

#11 Resolves Memory Issue
  9e/TTSJSON/ftc_base_v2.33.json
  9e/TTSJSON/ftc_base_v2.33.png
  9e/TTSLUA/9eScoreSheet.ttslua
  9e/TTSLUA/blueKustom40kDiceRollerMk3.ttslua
  9e/TTSLUA/redKustom40kDiceRollerMk3.ttslua
Labels: bug

#16 Added Pip Color Button
  9e/TTSJSON/ftc_base_v2.33.json
  9e/TTSLUA/blueDiceTable.ttslua
  9e/TTSLUA/redDiceTable.ttslua
Labels: enhancement

#18 Score Sheet - Encoding Keywords
  9e/TTSLUA/9eScoreSheet.ttslua
Labels: bug

#20 Save json compiler
  9e/TTSJSON/ftc_base_v2.33.json
  9e/TTSLUA/3SearchAndDestroy.ttslua
  9e/TTSLUA/40kItems.ttslua
  9e/TTSLUA/9eScoreSheet.ttslua
  9e/TTSLUA/armyPlacer.ttslua
  9e/TTSLUA/automacPsykicDeckBox.ttslua
  9e/TTSLUA/automacTokenBagsBox.ttslua
  9e/TTSLUA/blankObjectiveCard.ttslua
  9e/TTSLUA/blueDiceTable.ttslua
  9e/TTSLUA/blueHiddenZone.ttslua
  9e/TTSLUA/blueKustom40kDiceRollerMk3.ttslua
  9e/TTSLUA/bluePsykicPowers.ttslua
  9e/TTSLUA/blueTokens.ttslua
  9e/TTSLUA/blueTurns.ttslua
  9e/TTSLUA/ch1ScreenH.ttslua
  9e/TTSLUA/ch2ScreenH.ttslua
  9e/TTSLUA/ch6ScreenH.ttslua
  9e/TTSLUA/clock.ttslua
  9e/TTSLUA/customTile1.ttslua
  9e/TTSLUA/customTile2.ttslua
  9e/TTSLUA/customTile3.ttslua
  9e/TTSLUA/customTile4.ttslua
  9e/TTSLUA/customTile5.ttslua
  9e/TTSLUA/customTile6.ttslua
  9e/TTSLUA/customToken1.ttslua
  9e/TTSLUA/customToken2.ttslua
  9e/TTSLUA/customToken3.ttslua
  9e/TTSLUA/customToken4.ttslua
  9e/TTSLUA/customToken5.ttslua
  9e/TTSLUA/extractTerrain.ttslua
  9e/TTSLUA/flexTableControl.ttslua
  9e/TTSLUA/gameRounds.ttslua
  9e/TTSLUA/instructions.ttslua
  9e/TTSLUA/ktItems.ttslua
  9e/TTSLUA/matObjSurface.ttslua
  9e/TTSLUA/matUrl.ttslua
  9e/TTSLUA/redDiceTable.ttslua
  9e/TTSLUA/redHiddenZone.ttslua
  9e/TTSLUA/redKustom40kDiceRollerMk3.ttslua
  9e/TTSLUA/redPsykicPowers.ttslua
  9e/TTSLUA/redTokens.ttslua
  9e/TTSLUA/redTurns.ttslua
  9e/TTSLUA/secondaryObjectivesManagerBlue.ttslua
  9e/TTSLUA/secondaryObjectivesManagerRed.ttslua
  9e/TTSLUA/spawnGameTools.ttslua
  9e/TTSLUA/squadActivation.ttslua
  9e/TTSLUA/squadActivationBlue.ttslua
  9e/TTSLUA/squadActivationRed.ttslua
  9e/TTSLUA/startMenu.ttslua
  9e/TTSLUA/timer.ttslua
  9e/TTSLUA/woundsRemaining.ttslua
  9e/TTSLUA/woundsRemainingBlue.ttslua
  9e/TTSLUA/woundsRemainingRed.ttslua
  9e/compile.ps1
Labels: enhancement

#17 Updated deleteTable() in ExtractTerrain Object
  9e/TTSLUA/extractTerrain.ttslua
Labels: bug

#23 Cleanup of Compile.ps1
  9e/compile.ps1
Labels: cleanup

#24 Credits and Announcements Update
  9e/TTSJSON/ftc_base_v2.33.json
  9e/TTSLUA/global.ttslua
  9e/TTSLUA/startMenu.ttslua
Labels: cleanup

#26 Moved Objects to Keep from Overlapping
  9e/TTSJSON/ftc_base_v2.33.json
Labels: cleanup
